// Copyright Epic Games, Inc. All Rights Reserved.

using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using EpicGames.Core;
using UnrealBuildTool;

public class CreatureProgrammer : ModuleRules
{
	public CreatureProgrammer(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
	
		PublicDependencyModuleNames.AddRange(new string[]
		{
			"Core", "CoreUObject", "Engine", "InputCore", "EnhancedInput", "AnimationCore",
			"MeshDescription", "StaticMeshDescription"
		});

		PrivateDependencyModuleNames.AddRange(new string[] {  });

		GenerateCollisionChannelHeader();

		// Uncomment if you are using Slate UI
		// PrivateDependencyModuleNames.AddRange(new string[] { "Slate", "SlateCore" });

		// Uncomment if you are using online features
		// PrivateDependencyModuleNames.Add("OnlineSubsystem");

		// To include OnlineSubsystemSteam, add it to the plugins section in your uproject file with the Enabled attribute set to true
	}
	
	private void GenerateCollisionChannelHeader()
	{
		string ProjectDir = Path.GetFullPath(Path.Combine(ModuleDirectory, "..", ".."));
		string IniPath = Path.Combine(ProjectDir, "Config", "DefaultEngine.ini");

		var Lines = new List<string>
		{
			"// GENERATED by MyGame.Build.cs from DefaultEngine.ini — do not edit",
			"#pragma once",
			""
		};
		
		Lines.Add("#include \"Engine/EngineTypes.h\"");
		Lines.Add("namespace GameTraceChannel");
		Lines.Add("{");

		var Rx = new Regex(@"Channel=ECC_GameTraceChannel(\d+).*?Name=""([^""]+)""");
		foreach (string Line in File.ReadAllLines(IniPath))
		{
			
			// example
			// constexpr ECollisionChannel Ground = ECC_GameTraceChannel1;
			var M = Rx.Match(Line);
			if (M.Success)
				Lines.Add($"\tconstexpr ECollisionChannel {M.Groups[2].Value} = ECC_GameTraceChannel{M.Groups[1].Value};");
		}
		
		Lines.Add("}");

		string OutPath = Path.Combine(ModuleDirectory, "Generated", "CollisionChannels.h");
		DirectoryReference.CreateDirectory(new DirectoryReference(Path.Combine(ModuleDirectory, "Generated")));

		string NewContent = string.Join("\n", Lines) + "\n";
		// Only write on change — avoids dirtying timestamps and triggering rebuilds
		if (!File.Exists(OutPath) || File.ReadAllText(OutPath) != NewContent)
			File.WriteAllText(OutPath, NewContent);

		PublicIncludePaths.Add(Path.Combine(ModuleDirectory, "Generated"));
	}
}
